-- Migration: Track whether a weekly summary was produced by the Monday cron
-- or manually regenerated by an admin from the Clients page. Existing rows
-- predate the manual-regenerate flow, so they're treated as cron output.

ALTER TABLE weekly_summaries
  ADD COLUMN IF NOT EXISTS generated_by text NOT NULL DEFAULT 'cron'
    CHECK (generated_by IN ('cron', 'manual'));
