-- Migration: Weekly AI-generated summaries for brand client portal
-- One row per (brand_name, week_of). week_of is the Monday that starts the week.
-- Generated by a scheduled job that gathers visits + comments + status changes
-- and asks Gemini to produce a human-readable recap.

CREATE TABLE IF NOT EXISTS weekly_summaries (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_name   text        NOT NULL,
  week_of      date        NOT NULL,
  summary_md   text        NOT NULL,
  stats        jsonb       NOT NULL DEFAULT '{}'::jsonb,
  model        text,
  generated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (brand_name, week_of)
);

CREATE INDEX IF NOT EXISTS idx_weekly_summaries_brand_week
  ON weekly_summaries (brand_name, week_of DESC);

ALTER TABLE weekly_summaries ENABLE ROW LEVEL SECURITY;

-- Service role (API routes) bypasses RLS; no direct client access.
DROP POLICY IF EXISTS "no_client_access" ON weekly_summaries;
CREATE POLICY "no_client_access" ON weekly_summaries FOR SELECT USING (false);
